// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hmac_sha256_sha256_top_32_256_2 (
        mergeKopadStrm3_dout,
        mergeKopadStrm3_empty_n,
        mergeKopadStrm3_read,
        mergeKopadLenStrm4_dout,
        mergeKopadLenStrm4_empty_n,
        mergeKopadLenStrm4_read,
        eMergeKopadLenStrm5_dout,
        eMergeKopadLenStrm5_empty_n,
        eMergeKopadLenStrm5_read,
        hshStrm_TDATA,
        eHshStrm_TDATA,
        ap_clk,
        ap_rst,
        ap_start,
        hshStrm_TVALID,
        hshStrm_TREADY,
        eHshStrm_TVALID,
        eHshStrm_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] mergeKopadStrm3_dout;
input   mergeKopadStrm3_empty_n;
output   mergeKopadStrm3_read;
input  [63:0] mergeKopadLenStrm4_dout;
input   mergeKopadLenStrm4_empty_n;
output   mergeKopadLenStrm4_read;
input  [0:0] eMergeKopadLenStrm5_dout;
input   eMergeKopadLenStrm5_empty_n;
output   eMergeKopadLenStrm5_read;
output  [255:0] hshStrm_TDATA;
output  [7:0] eHshStrm_TDATA;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   hshStrm_TVALID;
input   hshStrm_TREADY;
output   eHshStrm_TVALID;
input   eHshStrm_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    preProcessing_U0_ap_start;
wire    preProcessing_U0_ap_done;
wire    preProcessing_U0_ap_continue;
wire    preProcessing_U0_ap_idle;
wire    preProcessing_U0_ap_ready;
wire    preProcessing_U0_mergeKopadStrm3_read;
wire    preProcessing_U0_mergeKopadLenStrm4_read;
wire    preProcessing_U0_eMergeKopadLenStrm5_read;
wire   [511:0] preProcessing_U0_blk_strm_din;
wire    preProcessing_U0_blk_strm_write;
wire   [63:0] preProcessing_U0_nblk_strm8_din;
wire    preProcessing_U0_nblk_strm8_write;
wire   [0:0] preProcessing_U0_end_nblk_strm11_din;
wire    preProcessing_U0_end_nblk_strm11_write;
wire    dup_strm_U0_ap_start;
wire    dup_strm_U0_ap_done;
wire    dup_strm_U0_ap_continue;
wire    dup_strm_U0_ap_idle;
wire    dup_strm_U0_ap_ready;
wire    dup_strm_U0_nblk_strm8_read;
wire    dup_strm_U0_end_nblk_strm11_read;
wire   [63:0] dup_strm_U0_nblk_strm19_din;
wire    dup_strm_U0_nblk_strm19_write;
wire   [0:0] dup_strm_U0_end_nblk_strm112_din;
wire    dup_strm_U0_end_nblk_strm112_write;
wire   [63:0] dup_strm_U0_nblk_strm210_din;
wire    dup_strm_U0_nblk_strm210_write;
wire   [0:0] dup_strm_U0_end_nblk_strm213_din;
wire    dup_strm_U0_end_nblk_strm213_write;
reg    ap_sync_reg_dup_strm_U0_ap_start;
wire    generateMsgSchedule_U0_ap_start;
wire    generateMsgSchedule_U0_ap_done;
wire    generateMsgSchedule_U0_ap_continue;
wire    generateMsgSchedule_U0_ap_idle;
wire    generateMsgSchedule_U0_ap_ready;
wire    generateMsgSchedule_U0_blk_strm_read;
wire    generateMsgSchedule_U0_nblk_strm19_read;
wire    generateMsgSchedule_U0_end_nblk_strm112_read;
wire   [31:0] generateMsgSchedule_U0_w_strm14_din;
wire    generateMsgSchedule_U0_w_strm14_write;
reg    ap_sync_reg_generateMsgSchedule_U0_ap_start;
wire    sha256Digest_256_3_U0_ap_start;
wire    sha256Digest_256_3_U0_ap_done;
wire    sha256Digest_256_3_U0_ap_continue;
wire    sha256Digest_256_3_U0_ap_idle;
wire    sha256Digest_256_3_U0_ap_ready;
wire    sha256Digest_256_3_U0_nblk_strm210_read;
wire    sha256Digest_256_3_U0_end_nblk_strm213_read;
wire    sha256Digest_256_3_U0_w_strm14_read;
wire   [255:0] sha256Digest_256_3_U0_hshStrm_TDATA;
wire    sha256Digest_256_3_U0_hshStrm_TVALID;
wire   [7:0] sha256Digest_256_3_U0_eHshStrm_TDATA;
wire    sha256Digest_256_3_U0_eHshStrm_TVALID;
reg    ap_sync_reg_sha256Digest_256_3_U0_ap_start;
wire    blk_strm_full_n;
wire   [511:0] blk_strm_dout;
wire   [5:0] blk_strm_num_data_valid;
wire   [5:0] blk_strm_fifo_cap;
wire    blk_strm_empty_n;
wire    nblk_strm_full_n;
wire   [63:0] nblk_strm_dout;
wire   [5:0] nblk_strm_num_data_valid;
wire   [5:0] nblk_strm_fifo_cap;
wire    nblk_strm_empty_n;
wire    end_nblk_strm_full_n;
wire   [0:0] end_nblk_strm_dout;
wire   [5:0] end_nblk_strm_num_data_valid;
wire   [5:0] end_nblk_strm_fifo_cap;
wire    end_nblk_strm_empty_n;
wire    nblk_strm1_full_n;
wire   [63:0] nblk_strm1_dout;
wire   [5:0] nblk_strm1_num_data_valid;
wire   [5:0] nblk_strm1_fifo_cap;
wire    nblk_strm1_empty_n;
wire    end_nblk_strm1_full_n;
wire   [0:0] end_nblk_strm1_dout;
wire   [5:0] end_nblk_strm1_num_data_valid;
wire   [5:0] end_nblk_strm1_fifo_cap;
wire    end_nblk_strm1_empty_n;
wire    nblk_strm2_full_n;
wire   [63:0] nblk_strm2_dout;
wire   [5:0] nblk_strm2_num_data_valid;
wire   [5:0] nblk_strm2_fifo_cap;
wire    nblk_strm2_empty_n;
wire    end_nblk_strm2_full_n;
wire   [0:0] end_nblk_strm2_dout;
wire   [5:0] end_nblk_strm2_num_data_valid;
wire   [5:0] end_nblk_strm2_fifo_cap;
wire    end_nblk_strm2_empty_n;
wire    w_strm_full_n;
wire   [31:0] w_strm_dout;
wire   [5:0] w_strm_num_data_valid;
wire   [5:0] w_strm_fifo_cap;
wire    w_strm_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_dup_strm_U0_ap_start = 1'b0;
#0 ap_sync_reg_generateMsgSchedule_U0_ap_start = 1'b0;
#0 ap_sync_reg_sha256Digest_256_3_U0_ap_start = 1'b0;
end

hmac_sha256_preProcessing preProcessing_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(preProcessing_U0_ap_start),
    .ap_done(preProcessing_U0_ap_done),
    .ap_continue(preProcessing_U0_ap_continue),
    .ap_idle(preProcessing_U0_ap_idle),
    .ap_ready(preProcessing_U0_ap_ready),
    .mergeKopadStrm3_dout(mergeKopadStrm3_dout),
    .mergeKopadStrm3_num_data_valid(3'd0),
    .mergeKopadStrm3_fifo_cap(3'd0),
    .mergeKopadStrm3_empty_n(mergeKopadStrm3_empty_n),
    .mergeKopadStrm3_read(preProcessing_U0_mergeKopadStrm3_read),
    .mergeKopadLenStrm4_dout(mergeKopadLenStrm4_dout),
    .mergeKopadLenStrm4_num_data_valid(3'd0),
    .mergeKopadLenStrm4_fifo_cap(3'd0),
    .mergeKopadLenStrm4_empty_n(mergeKopadLenStrm4_empty_n),
    .mergeKopadLenStrm4_read(preProcessing_U0_mergeKopadLenStrm4_read),
    .eMergeKopadLenStrm5_dout(eMergeKopadLenStrm5_dout),
    .eMergeKopadLenStrm5_num_data_valid(3'd0),
    .eMergeKopadLenStrm5_fifo_cap(3'd0),
    .eMergeKopadLenStrm5_empty_n(eMergeKopadLenStrm5_empty_n),
    .eMergeKopadLenStrm5_read(preProcessing_U0_eMergeKopadLenStrm5_read),
    .blk_strm_din(preProcessing_U0_blk_strm_din),
    .blk_strm_num_data_valid(blk_strm_num_data_valid),
    .blk_strm_fifo_cap(blk_strm_fifo_cap),
    .blk_strm_full_n(blk_strm_full_n),
    .blk_strm_write(preProcessing_U0_blk_strm_write),
    .nblk_strm8_din(preProcessing_U0_nblk_strm8_din),
    .nblk_strm8_num_data_valid(nblk_strm_num_data_valid),
    .nblk_strm8_fifo_cap(nblk_strm_fifo_cap),
    .nblk_strm8_full_n(nblk_strm_full_n),
    .nblk_strm8_write(preProcessing_U0_nblk_strm8_write),
    .end_nblk_strm11_din(preProcessing_U0_end_nblk_strm11_din),
    .end_nblk_strm11_num_data_valid(end_nblk_strm_num_data_valid),
    .end_nblk_strm11_fifo_cap(end_nblk_strm_fifo_cap),
    .end_nblk_strm11_full_n(end_nblk_strm_full_n),
    .end_nblk_strm11_write(preProcessing_U0_end_nblk_strm11_write)
);

hmac_sha256_dup_strm dup_strm_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dup_strm_U0_ap_start),
    .ap_done(dup_strm_U0_ap_done),
    .ap_continue(dup_strm_U0_ap_continue),
    .ap_idle(dup_strm_U0_ap_idle),
    .ap_ready(dup_strm_U0_ap_ready),
    .nblk_strm8_dout(nblk_strm_dout),
    .nblk_strm8_num_data_valid(nblk_strm_num_data_valid),
    .nblk_strm8_fifo_cap(nblk_strm_fifo_cap),
    .nblk_strm8_empty_n(nblk_strm_empty_n),
    .nblk_strm8_read(dup_strm_U0_nblk_strm8_read),
    .end_nblk_strm11_dout(end_nblk_strm_dout),
    .end_nblk_strm11_num_data_valid(end_nblk_strm_num_data_valid),
    .end_nblk_strm11_fifo_cap(end_nblk_strm_fifo_cap),
    .end_nblk_strm11_empty_n(end_nblk_strm_empty_n),
    .end_nblk_strm11_read(dup_strm_U0_end_nblk_strm11_read),
    .nblk_strm19_din(dup_strm_U0_nblk_strm19_din),
    .nblk_strm19_num_data_valid(nblk_strm1_num_data_valid),
    .nblk_strm19_fifo_cap(nblk_strm1_fifo_cap),
    .nblk_strm19_full_n(nblk_strm1_full_n),
    .nblk_strm19_write(dup_strm_U0_nblk_strm19_write),
    .end_nblk_strm112_din(dup_strm_U0_end_nblk_strm112_din),
    .end_nblk_strm112_num_data_valid(end_nblk_strm1_num_data_valid),
    .end_nblk_strm112_fifo_cap(end_nblk_strm1_fifo_cap),
    .end_nblk_strm112_full_n(end_nblk_strm1_full_n),
    .end_nblk_strm112_write(dup_strm_U0_end_nblk_strm112_write),
    .nblk_strm210_din(dup_strm_U0_nblk_strm210_din),
    .nblk_strm210_num_data_valid(nblk_strm2_num_data_valid),
    .nblk_strm210_fifo_cap(nblk_strm2_fifo_cap),
    .nblk_strm210_full_n(nblk_strm2_full_n),
    .nblk_strm210_write(dup_strm_U0_nblk_strm210_write),
    .end_nblk_strm213_din(dup_strm_U0_end_nblk_strm213_din),
    .end_nblk_strm213_num_data_valid(end_nblk_strm2_num_data_valid),
    .end_nblk_strm213_fifo_cap(end_nblk_strm2_fifo_cap),
    .end_nblk_strm213_full_n(end_nblk_strm2_full_n),
    .end_nblk_strm213_write(dup_strm_U0_end_nblk_strm213_write)
);

hmac_sha256_generateMsgSchedule generateMsgSchedule_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(generateMsgSchedule_U0_ap_start),
    .ap_done(generateMsgSchedule_U0_ap_done),
    .ap_continue(generateMsgSchedule_U0_ap_continue),
    .ap_idle(generateMsgSchedule_U0_ap_idle),
    .ap_ready(generateMsgSchedule_U0_ap_ready),
    .blk_strm_dout(blk_strm_dout),
    .blk_strm_num_data_valid(blk_strm_num_data_valid),
    .blk_strm_fifo_cap(blk_strm_fifo_cap),
    .blk_strm_empty_n(blk_strm_empty_n),
    .blk_strm_read(generateMsgSchedule_U0_blk_strm_read),
    .nblk_strm19_dout(nblk_strm1_dout),
    .nblk_strm19_num_data_valid(nblk_strm1_num_data_valid),
    .nblk_strm19_fifo_cap(nblk_strm1_fifo_cap),
    .nblk_strm19_empty_n(nblk_strm1_empty_n),
    .nblk_strm19_read(generateMsgSchedule_U0_nblk_strm19_read),
    .end_nblk_strm112_dout(end_nblk_strm1_dout),
    .end_nblk_strm112_num_data_valid(end_nblk_strm1_num_data_valid),
    .end_nblk_strm112_fifo_cap(end_nblk_strm1_fifo_cap),
    .end_nblk_strm112_empty_n(end_nblk_strm1_empty_n),
    .end_nblk_strm112_read(generateMsgSchedule_U0_end_nblk_strm112_read),
    .w_strm14_din(generateMsgSchedule_U0_w_strm14_din),
    .w_strm14_num_data_valid(w_strm_num_data_valid),
    .w_strm14_fifo_cap(w_strm_fifo_cap),
    .w_strm14_full_n(w_strm_full_n),
    .w_strm14_write(generateMsgSchedule_U0_w_strm14_write)
);

hmac_sha256_sha256Digest_256_3 sha256Digest_256_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sha256Digest_256_3_U0_ap_start),
    .ap_done(sha256Digest_256_3_U0_ap_done),
    .ap_continue(sha256Digest_256_3_U0_ap_continue),
    .ap_idle(sha256Digest_256_3_U0_ap_idle),
    .ap_ready(sha256Digest_256_3_U0_ap_ready),
    .nblk_strm210_dout(nblk_strm2_dout),
    .nblk_strm210_num_data_valid(nblk_strm2_num_data_valid),
    .nblk_strm210_fifo_cap(nblk_strm2_fifo_cap),
    .nblk_strm210_empty_n(nblk_strm2_empty_n),
    .nblk_strm210_read(sha256Digest_256_3_U0_nblk_strm210_read),
    .end_nblk_strm213_dout(end_nblk_strm2_dout),
    .end_nblk_strm213_num_data_valid(end_nblk_strm2_num_data_valid),
    .end_nblk_strm213_fifo_cap(end_nblk_strm2_fifo_cap),
    .end_nblk_strm213_empty_n(end_nblk_strm2_empty_n),
    .end_nblk_strm213_read(sha256Digest_256_3_U0_end_nblk_strm213_read),
    .w_strm14_dout(w_strm_dout),
    .w_strm14_num_data_valid(w_strm_num_data_valid),
    .w_strm14_fifo_cap(w_strm_fifo_cap),
    .w_strm14_empty_n(w_strm_empty_n),
    .w_strm14_read(sha256Digest_256_3_U0_w_strm14_read),
    .hshStrm_TDATA(sha256Digest_256_3_U0_hshStrm_TDATA),
    .hshStrm_TVALID(sha256Digest_256_3_U0_hshStrm_TVALID),
    .hshStrm_TREADY(hshStrm_TREADY),
    .eHshStrm_TDATA(sha256Digest_256_3_U0_eHshStrm_TDATA),
    .eHshStrm_TVALID(sha256Digest_256_3_U0_eHshStrm_TVALID),
    .eHshStrm_TREADY(eHshStrm_TREADY)
);

hmac_sha256_fifo_w512_d32_D_x blk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_blk_strm_din),
    .if_full_n(blk_strm_full_n),
    .if_write(preProcessing_U0_blk_strm_write),
    .if_dout(blk_strm_dout),
    .if_num_data_valid(blk_strm_num_data_valid),
    .if_fifo_cap(blk_strm_fifo_cap),
    .if_empty_n(blk_strm_empty_n),
    .if_read(generateMsgSchedule_U0_blk_strm_read)
);

hmac_sha256_fifo_w64_d32_D_x nblk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_nblk_strm8_din),
    .if_full_n(nblk_strm_full_n),
    .if_write(preProcessing_U0_nblk_strm8_write),
    .if_dout(nblk_strm_dout),
    .if_num_data_valid(nblk_strm_num_data_valid),
    .if_fifo_cap(nblk_strm_fifo_cap),
    .if_empty_n(nblk_strm_empty_n),
    .if_read(dup_strm_U0_nblk_strm8_read)
);

hmac_sha256_fifo_w1_d32_D_x end_nblk_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(preProcessing_U0_end_nblk_strm11_din),
    .if_full_n(end_nblk_strm_full_n),
    .if_write(preProcessing_U0_end_nblk_strm11_write),
    .if_dout(end_nblk_strm_dout),
    .if_num_data_valid(end_nblk_strm_num_data_valid),
    .if_fifo_cap(end_nblk_strm_fifo_cap),
    .if_empty_n(end_nblk_strm_empty_n),
    .if_read(dup_strm_U0_end_nblk_strm11_read)
);

hmac_sha256_fifo_w64_d32_D_x nblk_strm1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_nblk_strm19_din),
    .if_full_n(nblk_strm1_full_n),
    .if_write(dup_strm_U0_nblk_strm19_write),
    .if_dout(nblk_strm1_dout),
    .if_num_data_valid(nblk_strm1_num_data_valid),
    .if_fifo_cap(nblk_strm1_fifo_cap),
    .if_empty_n(nblk_strm1_empty_n),
    .if_read(generateMsgSchedule_U0_nblk_strm19_read)
);

hmac_sha256_fifo_w1_d32_D_x end_nblk_strm1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_end_nblk_strm112_din),
    .if_full_n(end_nblk_strm1_full_n),
    .if_write(dup_strm_U0_end_nblk_strm112_write),
    .if_dout(end_nblk_strm1_dout),
    .if_num_data_valid(end_nblk_strm1_num_data_valid),
    .if_fifo_cap(end_nblk_strm1_fifo_cap),
    .if_empty_n(end_nblk_strm1_empty_n),
    .if_read(generateMsgSchedule_U0_end_nblk_strm112_read)
);

hmac_sha256_fifo_w64_d32_D_x nblk_strm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_nblk_strm210_din),
    .if_full_n(nblk_strm2_full_n),
    .if_write(dup_strm_U0_nblk_strm210_write),
    .if_dout(nblk_strm2_dout),
    .if_num_data_valid(nblk_strm2_num_data_valid),
    .if_fifo_cap(nblk_strm2_fifo_cap),
    .if_empty_n(nblk_strm2_empty_n),
    .if_read(sha256Digest_256_3_U0_nblk_strm210_read)
);

hmac_sha256_fifo_w1_d32_D_x end_nblk_strm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dup_strm_U0_end_nblk_strm213_din),
    .if_full_n(end_nblk_strm2_full_n),
    .if_write(dup_strm_U0_end_nblk_strm213_write),
    .if_dout(end_nblk_strm2_dout),
    .if_num_data_valid(end_nblk_strm2_num_data_valid),
    .if_fifo_cap(end_nblk_strm2_fifo_cap),
    .if_empty_n(end_nblk_strm2_empty_n),
    .if_read(sha256Digest_256_3_U0_end_nblk_strm213_read)
);

hmac_sha256_fifo_w32_d32_D_x w_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(generateMsgSchedule_U0_w_strm14_din),
    .if_full_n(w_strm_full_n),
    .if_write(generateMsgSchedule_U0_w_strm14_write),
    .if_dout(w_strm_dout),
    .if_num_data_valid(w_strm_num_data_valid),
    .if_fifo_cap(w_strm_fifo_cap),
    .if_empty_n(w_strm_empty_n),
    .if_read(sha256Digest_256_3_U0_w_strm14_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dup_strm_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_dup_strm_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_generateMsgSchedule_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_generateMsgSchedule_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_sha256Digest_256_3_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_sha256Digest_256_3_U0_ap_start <= 1'b1;
        end
    end
end

assign ap_done = sha256Digest_256_3_U0_ap_done;

assign ap_idle = (sha256Digest_256_3_U0_ap_idle & preProcessing_U0_ap_idle & generateMsgSchedule_U0_ap_idle & dup_strm_U0_ap_idle);

assign ap_ready = preProcessing_U0_ap_ready;

assign dup_strm_U0_ap_continue = 1'b1;

assign dup_strm_U0_ap_start = (ap_sync_reg_dup_strm_U0_ap_start | ap_start);

assign eHshStrm_TDATA = sha256Digest_256_3_U0_eHshStrm_TDATA;

assign eHshStrm_TVALID = sha256Digest_256_3_U0_eHshStrm_TVALID;

assign eMergeKopadLenStrm5_read = preProcessing_U0_eMergeKopadLenStrm5_read;

assign generateMsgSchedule_U0_ap_continue = 1'b1;

assign generateMsgSchedule_U0_ap_start = (ap_sync_reg_generateMsgSchedule_U0_ap_start | ap_start);

assign hshStrm_TDATA = sha256Digest_256_3_U0_hshStrm_TDATA;

assign hshStrm_TVALID = sha256Digest_256_3_U0_hshStrm_TVALID;

assign mergeKopadLenStrm4_read = preProcessing_U0_mergeKopadLenStrm4_read;

assign mergeKopadStrm3_read = preProcessing_U0_mergeKopadStrm3_read;

assign preProcessing_U0_ap_continue = 1'b1;

assign preProcessing_U0_ap_start = ap_start;

assign sha256Digest_256_3_U0_ap_continue = ap_continue;

assign sha256Digest_256_3_U0_ap_start = (ap_sync_reg_sha256Digest_256_3_U0_ap_start | ap_start);

endmodule //hmac_sha256_sha256_top_32_256_2
