// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hmac_sha256_mergeKopad_32_64_256_32_64_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        kopad2Strm9_dout,
        kopad2Strm9_num_data_valid,
        kopad2Strm9_fifo_cap,
        kopad2Strm9_empty_n,
        kopad2Strm9_read,
        msgHashStrm10_dout,
        msgHashStrm10_num_data_valid,
        msgHashStrm10_fifo_cap,
        msgHashStrm10_empty_n,
        msgHashStrm10_read,
        eMsgHashStrm11_dout,
        eMsgHashStrm11_num_data_valid,
        eMsgHashStrm11_fifo_cap,
        eMsgHashStrm11_empty_n,
        eMsgHashStrm11_read,
        mergeKopadStrm3_din,
        mergeKopadStrm3_num_data_valid,
        mergeKopadStrm3_fifo_cap,
        mergeKopadStrm3_full_n,
        mergeKopadStrm3_write,
        mergeKopadLenStrm4_din,
        mergeKopadLenStrm4_num_data_valid,
        mergeKopadLenStrm4_fifo_cap,
        mergeKopadLenStrm4_full_n,
        mergeKopadLenStrm4_write,
        eMergeKopadLenStrm5_din,
        eMergeKopadLenStrm5_num_data_valid,
        eMergeKopadLenStrm5_fifo_cap,
        eMergeKopadLenStrm5_full_n,
        eMergeKopadLenStrm5_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] kopad2Strm9_dout;
input  [2:0] kopad2Strm9_num_data_valid;
input  [2:0] kopad2Strm9_fifo_cap;
input   kopad2Strm9_empty_n;
output   kopad2Strm9_read;
input  [255:0] msgHashStrm10_dout;
input  [2:0] msgHashStrm10_num_data_valid;
input  [2:0] msgHashStrm10_fifo_cap;
input   msgHashStrm10_empty_n;
output   msgHashStrm10_read;
input  [0:0] eMsgHashStrm11_dout;
input  [2:0] eMsgHashStrm11_num_data_valid;
input  [2:0] eMsgHashStrm11_fifo_cap;
input   eMsgHashStrm11_empty_n;
output   eMsgHashStrm11_read;
output  [31:0] mergeKopadStrm3_din;
input  [2:0] mergeKopadStrm3_num_data_valid;
input  [2:0] mergeKopadStrm3_fifo_cap;
input   mergeKopadStrm3_full_n;
output   mergeKopadStrm3_write;
output  [63:0] mergeKopadLenStrm4_din;
input  [2:0] mergeKopadLenStrm4_num_data_valid;
input  [2:0] mergeKopadLenStrm4_fifo_cap;
input   mergeKopadLenStrm4_full_n;
output   mergeKopadLenStrm4_write;
output  [0:0] eMergeKopadLenStrm5_din;
input  [2:0] eMergeKopadLenStrm5_num_data_valid;
input  [2:0] eMergeKopadLenStrm5_fifo_cap;
input   eMergeKopadLenStrm5_full_n;
output   eMergeKopadLenStrm5_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg kopad2Strm9_read;
reg msgHashStrm10_read;
reg eMsgHashStrm11_read;
reg[31:0] mergeKopadStrm3_din;
reg mergeKopadStrm3_write;
reg mergeKopadLenStrm4_write;
reg[0:0] eMergeKopadLenStrm5_din;
reg eMergeKopadLenStrm5_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    kopad2Strm9_blk_n;
wire    ap_CS_fsm_state2;
reg    msgHashStrm10_blk_n;
reg    eMsgHashStrm11_blk_n;
reg    mergeKopadLenStrm4_blk_n;
reg    eMergeKopadLenStrm5_blk_n;
reg   [511:0] kopad_V_reg_108;
reg   [255:0] msgHash_V_reg_113;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_idle;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready;
wire   [31:0] grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_din;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_write;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_idle;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready;
wire   [31:0] grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_din;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_write;
reg    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    ap_block_state2;
reg   [6:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_condition_152;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg = 1'b0;
#0 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg = 1'b0;
end

hmac_sha256_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start),
    .ap_done(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done),
    .ap_idle(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_idle),
    .ap_ready(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready),
    .mergeKopadStrm3_din(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_din),
    .mergeKopadStrm3_num_data_valid(3'd0),
    .mergeKopadStrm3_fifo_cap(3'd0),
    .mergeKopadStrm3_full_n(mergeKopadStrm3_full_n),
    .mergeKopadStrm3_write(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_write),
    .kopad_V_1(kopad_V_reg_108)
);

hmac_sha256_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start),
    .ap_done(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done),
    .ap_idle(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_idle),
    .ap_ready(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready),
    .mergeKopadStrm3_din(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_din),
    .mergeKopadStrm3_num_data_valid(3'd0),
    .mergeKopadStrm3_fifo_cap(3'd0),
    .mergeKopadStrm3_full_n(mergeKopadStrm3_full_n),
    .mergeKopadStrm3_write(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_write),
    .msgHash_V_1(msgHash_V_reg_113)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b1;
        end else if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready == 1'b1)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready == 1'b1)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kopad_V_reg_108 <= kopad2Strm9_dout;
        msgHash_V_reg_113 <= msgHashStrm10_dout;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        eMergeKopadLenStrm5_blk_n = eMergeKopadLenStrm5_full_n;
    end else begin
        eMergeKopadLenStrm5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_152)) begin
        if ((eMsgHashStrm11_dout == 1'd1)) begin
            eMergeKopadLenStrm5_din = 1'd1;
        end else if ((eMsgHashStrm11_dout == 1'd0)) begin
            eMergeKopadLenStrm5_din = 1'd0;
        end else begin
            eMergeKopadLenStrm5_din = 'bx;
        end
    end else begin
        eMergeKopadLenStrm5_din = 'bx;
    end
end

always @ (*) begin
    if (((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | (~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        eMergeKopadLenStrm5_write = 1'b1;
    end else begin
        eMergeKopadLenStrm5_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        eMsgHashStrm11_blk_n = eMsgHashStrm11_empty_n;
    end else begin
        eMsgHashStrm11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        eMsgHashStrm11_read = 1'b1;
    end else begin
        eMsgHashStrm11_read = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kopad2Strm9_blk_n = kopad2Strm9_empty_n;
    end else begin
        kopad2Strm9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kopad2Strm9_read = 1'b1;
    end else begin
        kopad2Strm9_read = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mergeKopadLenStrm4_blk_n = mergeKopadLenStrm4_full_n;
    end else begin
        mergeKopadLenStrm4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mergeKopadLenStrm4_write = 1'b1;
    end else begin
        mergeKopadLenStrm4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mergeKopadStrm3_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_din;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mergeKopadStrm3_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_din;
    end else begin
        mergeKopadStrm3_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mergeKopadStrm3_write = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm3_write;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mergeKopadStrm3_write = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm3_write;
    end else begin
        mergeKopadStrm3_write = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        msgHashStrm10_blk_n = msgHashStrm10_empty_n;
    end else begin
        msgHashStrm10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        msgHashStrm10_read = 1'b1;
    end else begin
        msgHashStrm10_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (eMsgHashStrm11_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_152 = (~((eMsgHashStrm11_empty_n == 1'b0) | ((eMsgHashStrm11_dout == 1'd1) & (eMergeKopadLenStrm5_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (msgHashStrm10_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (kopad2Strm9_empty_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (mergeKopadLenStrm4_full_n == 1'b0)) | ((eMsgHashStrm11_dout == 1'd0) & (eMergeKopadLenStrm5_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2));
end

assign grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg;

assign grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg;

assign mergeKopadLenStrm4_din = 64'd96;

endmodule //hmac_sha256_mergeKopad_32_64_256_32_64_s
