// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mergeKopadStrm3_dout,
        mergeKopadStrm3_num_data_valid,
        mergeKopadStrm3_fifo_cap,
        mergeKopadStrm3_empty_n,
        mergeKopadStrm3_read,
        p_cast,
        cmp130,
        cmp136,
        cmp153,
        b_M_16_out,
        b_M_16_out_ap_vld,
        b_M_15_out,
        b_M_15_out_ap_vld,
        b_M_14_out,
        b_M_14_out_ap_vld,
        b_M_13_out,
        b_M_13_out_ap_vld,
        b_M_12_out,
        b_M_12_out_ap_vld,
        b_M_11_out,
        b_M_11_out_ap_vld,
        b_M_10_out,
        b_M_10_out_ap_vld,
        b_M_9_out,
        b_M_9_out_ap_vld,
        b_M_8_out,
        b_M_8_out_ap_vld,
        b_M_7_out,
        b_M_7_out_ap_vld,
        b_M_6_out,
        b_M_6_out_ap_vld,
        b_M_5_out,
        b_M_5_out_ap_vld,
        b_M_4_out,
        b_M_4_out_ap_vld,
        b_M_3_out,
        b_M_3_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mergeKopadStrm3_dout;
input  [2:0] mergeKopadStrm3_num_data_valid;
input  [2:0] mergeKopadStrm3_fifo_cap;
input   mergeKopadStrm3_empty_n;
output   mergeKopadStrm3_read;
input  [3:0] p_cast;
input  [0:0] cmp130;
input  [0:0] cmp136;
input  [0:0] cmp153;
output  [31:0] b_M_16_out;
output   b_M_16_out_ap_vld;
output  [31:0] b_M_15_out;
output   b_M_15_out_ap_vld;
output  [31:0] b_M_14_out;
output   b_M_14_out_ap_vld;
output  [31:0] b_M_13_out;
output   b_M_13_out_ap_vld;
output  [31:0] b_M_12_out;
output   b_M_12_out_ap_vld;
output  [31:0] b_M_11_out;
output   b_M_11_out_ap_vld;
output  [31:0] b_M_10_out;
output   b_M_10_out_ap_vld;
output  [31:0] b_M_9_out;
output   b_M_9_out_ap_vld;
output  [31:0] b_M_8_out;
output   b_M_8_out_ap_vld;
output  [31:0] b_M_7_out;
output   b_M_7_out_ap_vld;
output  [31:0] b_M_6_out;
output   b_M_6_out_ap_vld;
output  [31:0] b_M_5_out;
output   b_M_5_out_ap_vld;
output  [31:0] b_M_4_out;
output   b_M_4_out_ap_vld;
output  [31:0] b_M_3_out;
output   b_M_3_out_ap_vld;

reg ap_idle;
reg mergeKopadStrm3_read;
reg b_M_16_out_ap_vld;
reg b_M_15_out_ap_vld;
reg b_M_14_out_ap_vld;
reg b_M_13_out_ap_vld;
reg b_M_12_out_ap_vld;
reg b_M_11_out_ap_vld;
reg b_M_10_out_ap_vld;
reg b_M_9_out_ap_vld;
reg b_M_8_out_ap_vld;
reg b_M_7_out_ap_vld;
reg b_M_6_out_ap_vld;
reg b_M_5_out_ap_vld;
reg b_M_4_out_ap_vld;
reg b_M_3_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln162_reg_1115;
reg   [0:0] icmp_ln170_reg_1119;
reg    ap_predicate_op106_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln160_fu_350_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mergeKopadStrm3_blk_n;
wire    ap_block_pp0_stage0;
wire   [0:0] cmp153_read_reg_1096;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] cmp136_read_reg_1100;
wire   [0:0] cmp130_read_read_fu_206_p2;
wire   [3:0] i_1_load_fu_347_p1;
reg   [3:0] i_1_reg_1108;
wire   [0:0] icmp_ln162_fu_362_p2;
wire   [0:0] icmp_ln170_fu_368_p2;
reg   [3:0] i_fu_134;
wire   [3:0] add_ln160_fu_356_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
reg   [31:0] b_M_fu_138;
wire   [31:0] b_M_18_fu_535_p2;
wire   [31:0] b_M_17_fu_625_p2;
wire   [31:0] b_M_16_fu_707_p2;
wire   [31:0] b_M_15_fu_797_p5;
reg   [31:0] b_M_1_fu_142;
reg   [31:0] b_M_2_fu_146;
reg   [31:0] b_M_3_fu_150;
reg   [31:0] b_M_4_fu_154;
reg   [31:0] b_M_5_fu_158;
reg   [31:0] b_M_6_fu_162;
reg   [31:0] b_M_7_fu_166;
reg   [31:0] b_M_8_fu_170;
reg   [31:0] b_M_9_fu_174;
reg   [31:0] b_M_10_fu_178;
reg   [31:0] b_M_11_fu_182;
reg   [31:0] b_M_12_fu_186;
reg   [31:0] b_M_13_fu_190;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] trunc_ln192_fu_519_p1;
wire   [7:0] grp_fu_322_p4;
wire   [7:0] grp_fu_332_p4;
wire   [31:0] or_ln5_fu_523_p5;
wire   [7:0] trunc_ln187_fu_611_p1;
wire   [31:0] or_ln4_fu_615_p4;
wire   [31:0] l_32_fu_701_p2;
wire   [7:0] empty_fu_783_p1;
wire   [7:0] p_s_fu_787_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_649;
reg    ap_condition_652;
reg    ap_condition_655;
reg    ap_condition_659;
reg    ap_condition_666;
reg    ap_condition_671;
reg    ap_condition_676;
reg    ap_condition_679;
reg    ap_condition_682;
reg    ap_condition_685;
reg    ap_condition_689;
reg    ap_condition_692;
reg    ap_condition_697;
reg    ap_condition_700;
reg    ap_condition_703;
reg    ap_condition_706;
reg    ap_condition_710;
reg    ap_condition_713;
reg    ap_condition_716;
reg    ap_condition_719;
reg    ap_condition_722;
reg    ap_condition_725;
reg    ap_condition_728;
reg    ap_condition_731;
reg    ap_condition_736;
reg    ap_condition_739;
reg    ap_condition_742;
reg    ap_condition_745;
reg    ap_condition_749;
reg    ap_condition_752;
reg    ap_condition_757;
reg    ap_condition_760;
reg    ap_condition_763;
reg    ap_condition_766;
reg    ap_condition_770;
reg    ap_condition_773;
reg    ap_condition_778;
reg    ap_condition_781;
reg    ap_condition_784;
reg    ap_condition_787;
reg    ap_condition_791;
reg    ap_condition_794;
reg    ap_condition_799;
reg    ap_condition_802;
reg    ap_condition_805;
reg    ap_condition_808;
reg    ap_condition_812;
reg    ap_condition_815;
reg    ap_condition_820;
reg    ap_condition_823;
reg    ap_condition_826;
reg    ap_condition_829;
reg    ap_condition_833;
reg    ap_condition_836;
reg    ap_condition_841;
reg    ap_condition_844;
reg    ap_condition_847;
reg    ap_condition_850;
reg    ap_condition_854;
reg    ap_condition_857;
reg    ap_condition_862;
reg    ap_condition_865;
reg    ap_condition_868;
reg    ap_condition_871;
reg    ap_condition_875;
reg    ap_condition_878;
reg    ap_condition_883;
reg    ap_condition_886;
reg    ap_condition_889;
reg    ap_condition_892;
reg    ap_condition_896;
reg    ap_condition_899;
reg    ap_condition_904;
reg    ap_condition_907;
reg    ap_condition_910;
reg    ap_condition_913;
reg    ap_condition_917;
reg    ap_condition_920;
reg    ap_condition_925;
reg    ap_condition_928;
reg    ap_condition_931;
reg    ap_condition_934;
reg    ap_condition_938;
reg    ap_condition_941;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hmac_sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_671)) begin
            b_M_10_fu_178 <= 32'd0;
        end else if ((1'b1 == ap_condition_666)) begin
            b_M_10_fu_178 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_659)) begin
            b_M_10_fu_178 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_655)) begin
            b_M_10_fu_178 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_652)) begin
            b_M_10_fu_178 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_649)) begin
            b_M_10_fu_178 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_692)) begin
            b_M_11_fu_182 <= 32'd0;
        end else if ((1'b1 == ap_condition_689)) begin
            b_M_11_fu_182 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_685)) begin
            b_M_11_fu_182 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_682)) begin
            b_M_11_fu_182 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_679)) begin
            b_M_11_fu_182 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_676)) begin
            b_M_11_fu_182 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_713)) begin
            b_M_12_fu_186 <= 32'd0;
        end else if ((1'b1 == ap_condition_710)) begin
            b_M_12_fu_186 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_706)) begin
            b_M_12_fu_186 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_703)) begin
            b_M_12_fu_186 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_700)) begin
            b_M_12_fu_186 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_697)) begin
            b_M_12_fu_186 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_731)) begin
            b_M_13_fu_190 <= 32'd0;
        end else if ((1'b1 == ap_condition_728)) begin
            b_M_13_fu_190 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_725)) begin
            b_M_13_fu_190 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_722)) begin
            b_M_13_fu_190 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_719)) begin
            b_M_13_fu_190 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_716)) begin
            b_M_13_fu_190 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_752)) begin
            b_M_1_fu_142 <= 32'd0;
        end else if ((1'b1 == ap_condition_749)) begin
            b_M_1_fu_142 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_745)) begin
            b_M_1_fu_142 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_742)) begin
            b_M_1_fu_142 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_739)) begin
            b_M_1_fu_142 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_736)) begin
            b_M_1_fu_142 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_773)) begin
            b_M_2_fu_146 <= 32'd0;
        end else if ((1'b1 == ap_condition_770)) begin
            b_M_2_fu_146 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_766)) begin
            b_M_2_fu_146 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_763)) begin
            b_M_2_fu_146 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_760)) begin
            b_M_2_fu_146 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_757)) begin
            b_M_2_fu_146 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_794)) begin
            b_M_3_fu_150 <= 32'd0;
        end else if ((1'b1 == ap_condition_791)) begin
            b_M_3_fu_150 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_787)) begin
            b_M_3_fu_150 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_784)) begin
            b_M_3_fu_150 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_781)) begin
            b_M_3_fu_150 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_778)) begin
            b_M_3_fu_150 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_815)) begin
            b_M_4_fu_154 <= 32'd0;
        end else if ((1'b1 == ap_condition_812)) begin
            b_M_4_fu_154 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_808)) begin
            b_M_4_fu_154 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_805)) begin
            b_M_4_fu_154 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_802)) begin
            b_M_4_fu_154 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_799)) begin
            b_M_4_fu_154 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_836)) begin
            b_M_5_fu_158 <= 32'd0;
        end else if ((1'b1 == ap_condition_833)) begin
            b_M_5_fu_158 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_829)) begin
            b_M_5_fu_158 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_826)) begin
            b_M_5_fu_158 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_823)) begin
            b_M_5_fu_158 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_820)) begin
            b_M_5_fu_158 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_857)) begin
            b_M_6_fu_162 <= 32'd0;
        end else if ((1'b1 == ap_condition_854)) begin
            b_M_6_fu_162 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_850)) begin
            b_M_6_fu_162 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_847)) begin
            b_M_6_fu_162 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_844)) begin
            b_M_6_fu_162 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_841)) begin
            b_M_6_fu_162 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_878)) begin
            b_M_7_fu_166 <= 32'd0;
        end else if ((1'b1 == ap_condition_875)) begin
            b_M_7_fu_166 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_871)) begin
            b_M_7_fu_166 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_868)) begin
            b_M_7_fu_166 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_865)) begin
            b_M_7_fu_166 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_862)) begin
            b_M_7_fu_166 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_899)) begin
            b_M_8_fu_170 <= 32'd0;
        end else if ((1'b1 == ap_condition_896)) begin
            b_M_8_fu_170 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_892)) begin
            b_M_8_fu_170 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_889)) begin
            b_M_8_fu_170 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_886)) begin
            b_M_8_fu_170 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_883)) begin
            b_M_8_fu_170 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_920)) begin
            b_M_9_fu_174 <= 32'd0;
        end else if ((1'b1 == ap_condition_917)) begin
            b_M_9_fu_174 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_913)) begin
            b_M_9_fu_174 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_910)) begin
            b_M_9_fu_174 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_907)) begin
            b_M_9_fu_174 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_904)) begin
            b_M_9_fu_174 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_941)) begin
            b_M_fu_138 <= 32'd0;
        end else if ((1'b1 == ap_condition_938)) begin
            b_M_fu_138 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_934)) begin
            b_M_fu_138 <= b_M_15_fu_797_p5;
        end else if ((1'b1 == ap_condition_931)) begin
            b_M_fu_138 <= b_M_16_fu_707_p2;
        end else if ((1'b1 == ap_condition_928)) begin
            b_M_fu_138 <= b_M_17_fu_625_p2;
        end else if ((1'b1 == ap_condition_925)) begin
            b_M_fu_138 <= b_M_18_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_134 <= add_ln160_fu_356_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_134 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_1108 <= ap_sig_allocacmp_i_1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_350_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln162_reg_1115 <= icmp_ln162_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_350_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln162_fu_362_p2 == 1'd0))) begin
        icmp_ln170_reg_1119 <= icmp_ln170_fu_368_p2;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_134;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_10_out_ap_vld = 1'b1;
    end else begin
        b_M_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_11_out_ap_vld = 1'b1;
    end else begin
        b_M_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_12_out_ap_vld = 1'b1;
    end else begin
        b_M_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_13_out_ap_vld = 1'b1;
    end else begin
        b_M_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_14_out_ap_vld = 1'b1;
    end else begin
        b_M_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_15_out_ap_vld = 1'b1;
    end else begin
        b_M_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_16_out_ap_vld = 1'b1;
    end else begin
        b_M_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_3_out_ap_vld = 1'b1;
    end else begin
        b_M_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_4_out_ap_vld = 1'b1;
    end else begin
        b_M_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_5_out_ap_vld = 1'b1;
    end else begin
        b_M_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_6_out_ap_vld = 1'b1;
    end else begin
        b_M_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_7_out_ap_vld = 1'b1;
    end else begin
        b_M_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_8_out_ap_vld = 1'b1;
    end else begin
        b_M_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_M_9_out_ap_vld = 1'b1;
    end else begin
        b_M_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op106_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mergeKopadStrm3_blk_n = mergeKopadStrm3_empty_n;
    end else begin
        mergeKopadStrm3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op106_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mergeKopadStrm3_read = 1'b1;
    end else begin
        mergeKopadStrm3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_356_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln162_reg_1115 == 1'd1) & (mergeKopadStrm3_empty_n == 1'b0)) | ((ap_predicate_op106_read_state2 == 1'b1) & (mergeKopadStrm3_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln162_reg_1115 == 1'd1) & (mergeKopadStrm3_empty_n == 1'b0)) | ((ap_predicate_op106_read_state2 == 1'b1) & (mergeKopadStrm3_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln162_reg_1115 == 1'd1) & (mergeKopadStrm3_empty_n == 1'b0)) | ((ap_predicate_op106_read_state2 == 1'b1) & (mergeKopadStrm3_empty_n == 1'b0))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((icmp_ln162_reg_1115 == 1'd1) & (mergeKopadStrm3_empty_n == 1'b0)) | ((ap_predicate_op106_read_state2 == 1'b1) & (mergeKopadStrm3_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_649 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd10) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_652 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd10) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_655 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd10) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_659 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd10));
end

always @ (*) begin
    ap_condition_666 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd10) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_671 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd10));
end

always @ (*) begin
    ap_condition_676 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd11) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_679 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd11) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_682 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd11) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_685 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd11));
end

always @ (*) begin
    ap_condition_689 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd11) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_692 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd11));
end

always @ (*) begin
    ap_condition_697 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd12) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_700 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd12) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_703 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd12) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_706 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd12));
end

always @ (*) begin
    ap_condition_710 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd12) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_713 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd12));
end

always @ (*) begin
    ap_condition_716 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd14) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0)) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd15) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0))) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd13) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0))));
end

always @ (*) begin
    ap_condition_719 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd14) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1)) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd15) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1))) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd13) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1))));
end

always @ (*) begin
    ap_condition_722 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd14) & (cmp136_read_reg_1100 == 1'd1)) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd15) & (cmp136_read_reg_1100 == 1'd1))) | ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (i_1_reg_1108 == 4'd13) & (cmp136_read_reg_1100 == 1'd1))));
end

always @ (*) begin
    ap_condition_725 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((icmp_ln162_reg_1115 == 1'd1) & (i_1_reg_1108 == 4'd14)) | ((icmp_ln162_reg_1115 == 1'd1) & (i_1_reg_1108 == 4'd15))) | ((icmp_ln162_reg_1115 == 1'd1) & (i_1_reg_1108 == 4'd13))));
end

always @ (*) begin
    ap_condition_728 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd14) & (cmp130_read_read_fu_206_p2 == 1'd1)) | ((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd15) & (cmp130_read_read_fu_206_p2 == 1'd1))) | ((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd13) & (cmp130_read_read_fu_206_p2 == 1'd1))));
end

always @ (*) begin
    ap_condition_731 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd14)) | ((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd15))) | ((icmp_ln160_fu_350_p2 == 1'd0) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd13))));
end

always @ (*) begin
    ap_condition_736 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd1) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_739 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd1) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_742 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd1) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_745 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd1));
end

always @ (*) begin
    ap_condition_749 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd1) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_752 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd1));
end

always @ (*) begin
    ap_condition_757 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd2) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_760 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd2) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_763 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd2) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_766 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd2));
end

always @ (*) begin
    ap_condition_770 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd2) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_773 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd2));
end

always @ (*) begin
    ap_condition_778 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd3) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_781 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd3) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_784 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd3) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_787 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd3));
end

always @ (*) begin
    ap_condition_791 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd3) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_794 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd3));
end

always @ (*) begin
    ap_condition_799 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd4) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_802 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd4) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_805 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd4) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_808 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd4));
end

always @ (*) begin
    ap_condition_812 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd4) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_815 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd4));
end

always @ (*) begin
    ap_condition_820 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd5) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_823 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd5) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_826 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd5) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_829 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd5));
end

always @ (*) begin
    ap_condition_833 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd5) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_836 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd5));
end

always @ (*) begin
    ap_condition_841 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd6) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_844 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd6) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_847 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd6) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_850 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd6));
end

always @ (*) begin
    ap_condition_854 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd6) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_857 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd6));
end

always @ (*) begin
    ap_condition_862 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd7) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_865 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd7) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_868 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd7) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_871 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd7));
end

always @ (*) begin
    ap_condition_875 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd7) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_878 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd7));
end

always @ (*) begin
    ap_condition_883 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd8) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_886 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd8) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_889 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd8) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_892 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd8));
end

always @ (*) begin
    ap_condition_896 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd8) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_899 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd8));
end

always @ (*) begin
    ap_condition_904 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd9) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_907 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd9) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_910 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd9) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_913 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd9));
end

always @ (*) begin
    ap_condition_917 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd9) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_920 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd9));
end

always @ (*) begin
    ap_condition_925 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd0) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd0));
end

always @ (*) begin
    ap_condition_928 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd0) & (cmp136_read_reg_1100 == 1'd0) & (cmp153_read_reg_1096 == 1'd1));
end

always @ (*) begin
    ap_condition_931 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd0) & (cmp136_read_reg_1100 == 1'd1));
end

always @ (*) begin
    ap_condition_934 = ((icmp_ln162_reg_1115 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1108 == 4'd0));
end

always @ (*) begin
    ap_condition_938 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd0) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd0) & (cmp130_read_read_fu_206_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_941 = ((icmp_ln160_fu_350_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln170_fu_368_p2 == 1'd1) & (icmp_ln162_fu_362_p2 == 1'd0) & (i_1_load_fu_347_p1 == 4'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op106_read_state2 = ((cmp130 == 1'd0) & (icmp_ln170_reg_1119 == 1'd0) & (icmp_ln162_reg_1115 == 1'd0));
end

assign b_M_10_out = b_M_7_fu_166;

assign b_M_11_out = b_M_8_fu_170;

assign b_M_12_out = b_M_9_fu_174;

assign b_M_13_out = b_M_10_fu_178;

assign b_M_14_out = b_M_11_fu_182;

assign b_M_15_fu_797_p5 = {{{{empty_fu_783_p1}, {grp_fu_322_p4}}, {grp_fu_332_p4}}, {p_s_fu_787_p4}};

assign b_M_15_out = b_M_12_fu_186;

assign b_M_16_fu_707_p2 = (l_32_fu_701_p2 | 32'd8388608);

assign b_M_16_out = b_M_13_fu_190;

assign b_M_17_fu_625_p2 = (or_ln4_fu_615_p4 | 32'd32768);

assign b_M_18_fu_535_p2 = (or_ln5_fu_523_p5 | 32'd128);

assign b_M_3_out = b_M_fu_138;

assign b_M_4_out = b_M_1_fu_142;

assign b_M_5_out = b_M_2_fu_146;

assign b_M_6_out = b_M_3_fu_150;

assign b_M_7_out = b_M_4_fu_154;

assign b_M_8_out = b_M_5_fu_158;

assign b_M_9_out = b_M_6_fu_162;

assign cmp130_read_read_fu_206_p2 = cmp130;

assign cmp136_read_reg_1100 = cmp136;

assign cmp153_read_reg_1096 = cmp153;

assign empty_fu_783_p1 = mergeKopadStrm3_dout[7:0];

assign grp_fu_322_p4 = {{mergeKopadStrm3_dout[15:8]}};

assign grp_fu_332_p4 = {{mergeKopadStrm3_dout[23:16]}};

assign i_1_load_fu_347_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln160_fu_350_p2 = ((ap_sig_allocacmp_i_1 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_362_p2 = ((ap_sig_allocacmp_i_1 < p_cast) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_368_p2 = ((ap_sig_allocacmp_i_1 > p_cast) ? 1'b1 : 1'b0);

assign l_32_fu_701_p2 = mergeKopadStrm3_dout << 32'd24;

assign or_ln4_fu_615_p4 = {{{trunc_ln187_fu_611_p1}, {grp_fu_322_p4}}, {16'd0}};

assign or_ln5_fu_523_p5 = {{{{trunc_ln192_fu_519_p1}, {grp_fu_322_p4}}, {grp_fu_332_p4}}, {8'd0}};

assign p_s_fu_787_p4 = {{mergeKopadStrm3_dout[31:24]}};

assign trunc_ln187_fu_611_p1 = mergeKopadStrm3_dout[7:0];

assign trunc_ln192_fu_519_p1 = mergeKopadStrm3_dout[7:0];

endmodule //hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE
